### ISSUE TITLE
About the entire datasets

### ISSUE THREAD

**Issue by hmf21** [YuanXiong/NAVELoc#1]
Thanks for your impressive work and sharing.
It seems that the link you offer only contains the GovFacility images.
Could you please release all the other dataset such as Campus and snowytown.

And the renderings folder seems to need a password to extract, could you please release the password at the same time?

Looking forward to your reply!

**Comment by YuanXiong** [comment]
I guess that you are Chinese so I will reply in Chinese.

感谢你关注我的论文数据集，我最近刚刚博士毕业，正在整理材料。由于我已经毕业了，稍微有点自由了，所以我可以公开数据集了。不过我需要用一整个暑假整理一下数据，毕竟图片有点多，大小有几百个G，拷贝到OneDrive需要花好几周时间。解压缩的密码是我的学号：BY1906052。你可以先试用GovFacility这个数据集进行训练和测试，因为这是最简单的一个数据集，如果你觉得有用，可以再向我要剩余的数据集。我不清楚你是否急着用，如果很急的话，你可以告诉我，我争取快点。
________________________________
发件人: Mengfan He ***@***.***>
发送时间: 2024年3月23日 2:53
收件人: YuanXiong/NAVELoc ***@***.***>
抄送: Subscribed ***@***.***>
主题: [YuanXiong/NAVELoc] About the entire datasets (Issue #1)


Thanks for your impressive work and sharing.
It seems that the link you offer only contains the GovFacility images.
Could you please release all the other dataset such as Campus and snowytown.

And the renderings folder seems to need a password to extract, could you please release the password at the same time?

Looking forward to your reply!

―

**Comment by hmf21** [comment]
谢谢您的分享和整理，我先试用GovFacility这个数据集进行训练和测试。您先处理您的事务，也期待后续整体数据集的公开！
